services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - /home/saransh/.kube:/root/.kube:ro
    networks:
      - default
      - kind
    env_file:
      - ./backend/.env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./frontend/.env.local
    networks:
      - default
    depends_on:
      - backend
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped

networks:
  default:
  kind:
    external: true
